name: ci
on:
  push:
    branches:
      - "rootfs"
jobs:
#   scan:
#     permissions:
#       contents: read
#       security-events: write
#       actions: read
#     name: Build
#     runs-on: "ubuntu-20.04"
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build an image from Dockerfile
#         run: |
#           docker build -t docker.io/yynoam/masaratapp:${{ github.sha }} .

#       - name: Run Trivy vulnerability scanner
#         uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
#         with:
#           image-ref: 'docker.io/yynoam/masaratapp:${{ github.sha }}'
#           format: 'template'
#           template: '@/contrib/sarif.tpl'
#           severity: 'CRITICAL,HIGH'

#   push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/masaratapp:latest
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner with rootfs command
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          scan-ref: 'rootfs-example-binary'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

