name: ci
on:
  push:
    branches:
      - "*"
jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/yynoam/masaratapp:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/yynoam/masaratapp:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  push:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/masaratapp:${{ secrets.VERSION }}

      - name: Autoincrement a new patch version
        run: |
          echo "NEW_VERSION=$((${{ secrets.VERSION }}+1))" >> $GITHUB_ENV


      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
            repository: yssefnoam/masaratAppIac
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: modify the image
        run: |
            # git config user.email 2020noam@gmail.com
            # git config user.name yssefnoam
            # pwd
            cat kubernetes/deployment.yaml
            # pwd
            # sed -i "s+tanmay238/images.*+tanmay238/images:app-${{ secrets.VERSION }}+g" kubernetes/deployment.yaml
            sed -i 's/\(image: yynoam\/masaratapp:\)\(.*\)/image: yynoam\/masaratapp:${{ secrets.VERSION }}/g' kubernetes/deployment.yaml
            cat kubernetes/deployment.yaml
            # git add .
            # git commit -m 'Done  by Github Actions   Job change manifest: ${{ secrets.VERSION }}'
            # git push origin main
        env:
            GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
            RUN_NUMBER: ${{ github.run_number }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
            author_name: yssefnoam
            author_email: 2020noam@gmail.com
            message: 'Done by Github Action'
            add: './kubernetes/deployment.yaml'

    #   - name: Update patch version
    #     uses: hmanzur/actions-set-secret@v2.0.0
    #     with:
    #         name: 'VERSION'
    #         value: ${{ env.NEW_VERSION }}
    #         repository: yssefnoam/masaratApp
    #         token: ${{ secrets.REPO_ACCESS_TOKEN }}
