name: ci
on:
  push:
    branches:
      - "workflow-test"
# jobs:
#   build:
#         name: Build
#         runs-on: ubuntu-20.04
#         steps:
#         - name: Checkout code
#           uses: actions/checkout@v3

#         - name: Build an image from Dockerfile
#           run: |
#             docker build -t ${{ github.sha }} .

#         - name: Run Trivy vulnerability scanner
#           uses: aquasecurity/trivy-action@master
#           with:
#             image-ref: '${{ github.sha }}'
#             format: 'sarif'
#             output: 'trivy-results.sarif'
#             severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

#         - name: Upload Trivy scan results to GitHub Security tab
#           uses: github/codeql-action/upload-sarif@v2
#           with:
#             sarif_file: 'trivy-results.sarif'
# jobs:
#     security:
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@master
#         - name: Run Snyk to check for vulnerabilities
#           uses: snyk/actions/node@master
#           env:
#             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
# jobs:
#   snyk:
#     permissions:
#       contents: read # for actions/checkout to fetch code
#       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Snyk CLI to check for security issues
#         uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

#       - name: Snyk Code test
#         run: snyk code test 

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout
# #         uses: actions/checkout@v4

# #       - name: Login to Docker Hub
# #         uses: docker/login-action@v3
# #         with:
# #           username: ${{ secrets.DOCKERHUB_USERNAME }}
# #           password: ${{ secrets.DOCKERHUB_TOKEN }}

# #       - name: Set up Docker Buildx
# #         uses: docker/setup-buildx-action@v3

# #       - name: Build and push
# #         uses: docker/build-push-action@v5
# #         with:
# #           context: .
# #           file: ./Dockerfile
# #           push: true
# #           tags: ${{ secrets.DOCKERHUB_USERNAME }}/masaratapp:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Image"
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/masaratapp:${{ github.sha }}

      - name: Run Trivy vulnerability Scanner Before Push
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/masaratapp:${{ github.sha }}"
          format: "template"
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: "Push Scanned Image to docker hub"
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/masaratapp:${{ github.sha }}
